name: Build and Deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    #strategy:
      #matrix:
        #maven: [3.9.6, 3.9.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: bucket # Replace 'main' with the name of the branch you want to checkout

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Maven
        uses: hb0730/maven-action@v1.0.2
        with:
          url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          maven-verison: 3.9.6
          #java-version: '17'
          #maven-version: ${{ matrix.maven-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 4.4
   
      - name: Build with Maven        
        run: |
          mvn --version
          ls -la
          mvn clean
          mvn install

      - name: Display with tree cmd        
        run: |
         ls -la 
         ls -la target
      
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: app-design-0.0.1-SNAPSHOT.jar
          target: /home/opc/
