name: Build and Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: bucket # Replace 'main' with the name of the branch you want to checkout

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Display content
        run: ls -la 

      #- name: Deploy to EC2 instance
        #run: |
          # Replace the following command with your deployment script
          #echo "Deploying to EC2 instance..."
