name: Build and Deploy

on:
  push:
    branches:
      - "bucket"

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: bucket # Replace 'main' with the name of the branch you want to checkout

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Maven
        uses: hb0730/maven-action@v1.0.2
        with:
          url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          maven-verison: 3.9.6

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 4.4
   
      - name: Build with Maven        
        run: |
          mvn --version
          #ls -la
          #mvn clean
          #mvn install

      - name: Display with tree cmd        
        run: |
         ls -la 
         #ls -la target
      
